apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: count-ingress
  namespace: count-system
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/count-items
        pathType: Prefix
        backend:
          service:
            name: count-management-service
            port:
              number: 8080
      - path: /ui
        pathType: Prefix
        backend:
          service:
            name: count-management-service
            port:
              number: 8080
